Repository ExchangeUnion/xud-docker, pull requests merged in 2020-06, with the labels that each got.

#366 feat(launcher): light mode v2 - command line options
  images/connext/latest/Dockerfile
  images/connext/latest/Dockerfile.aarch64
  images/raiden/0.100.5a1.dev162-2217bcb-simnet/Dockerfile
  images/raiden/0.100.5a1.dev162-2217bcb-simnet/entrypoint.sh
  images/raiden/0.100.5a1.dev162-2217bcb-simnet/onboarder.py
  images/raiden/0.100.5a1.dev162-2217bcb-simnet/supervisord.conf
  images/raiden/0.100.5a1.dev162-2217bcb/Dockerfile
  images/raiden/0.100.5a1.dev162-2217bcb/entrypoint.sh
  images/raiden/0.100.5a1.dev162-2217bcb/supervisord.conf
  images/raiden/develop/Dockerfile
  images/raiden/develop/entrypoint.sh
  images/raiden/develop/onboarder.py
  images/utils/launcher/__init__.py
  images/utils/launcher/config/config.py
  images/utils/launcher/config/errors.py
  images/utils/launcher/config/loader.py
  images/utils/launcher/config/mainnet.conf
  images/utils/launcher/config/simnet.conf
  images/utils/launcher/config/template.py
  images/utils/launcher/config/testnet.conf
  images/utils/launcher/node/__init__.py
  images/utils/launcher/node/bitcoind.py
  images/utils/launcher/node/connext.py
  images/utils/launcher/node/geth.py
  images/utils/launcher/node/lnd.py
  images/utils/launcher/node/raiden.py
  images/utils/launcher/types.py
Labels: P1

#483 feat(xudctl): add confirmation before down command
  images/utils/launcher/shell/shell.py
Labels: P2

#484 feat(launcher): do not create conf file if missing
  images/utils/launcher/check_wallets.py
  images/utils/launcher/config/config.py
  images/utils/launcher/config/loader.py
Labels: P2

#505 chore: upgrade geth 1.9.14 -> 1.9.15
  images/geth/1.9.15/Dockerfile
  images/geth/1.9.15/entrypoint.sh
  images/geth/1.9.15/mainnet-peers.txt
  images/geth/1.9.15/rinkeby-peers.txt
  images/utils/launcher/config/template.py
Labels: P3

#514 feat: add michael's geth on clearnet
  images/utils/launcher/config/template.py
Labels: P2

#515 fix(xud): xud.conf disable raiden, enable connext
  images/xud/1.0.0-beta.3/entrypoint.sh
Labels: P2, bug

#516 Update README.md
  README.md
Labels: P3

#530 Add LICENSE
  LICENSE
Labels: P3

#529 feat: set testnet/mainnet graph update delay from default 90s to 15s
  images/lnd/0.10.1-beta/lnd.conf
  images/lnd/0.9.0-beta-ltc/lnd.conf
Labels: P2, enhancement

#537 chore: remove image timestamp comparison
  images/utils/launcher/config/config.py
  images/utils/launcher/config/template.py
  images/utils/launcher/node/image.py
  setup.sh
Labels: P1

#513 chore(xudctl): refine connext status
  images/utils/launcher/node/__init__.py
  images/utils/launcher/node/base.py
  images/utils/launcher/node/connext.py
Labels: P2

#554 chore: upgrade lndltc 0.9.0 -> 0.10.1
  images/lnd/0.10.1-beta-ltc-simnet/Dockerfile
  images/lnd/0.10.1-beta-ltc-simnet/entrypoint.sh
  images/lnd/0.10.1-beta-ltc-simnet/patches/fundingmanager-ltc.patch
  images/lnd/0.10.1-beta-ltc-simnet/patches/limits.patch
  images/lnd/0.10.1-beta-ltc-simnet/patches/lnd.patch
  images/lnd/0.10.1-beta-ltc-simnet/patches/neutrino.patch
  images/lnd/0.10.1-beta-ltc/Dockerfile
  images/lnd/0.10.1-beta-ltc/entrypoint.sh
  images/lnd/0.10.1-beta-ltc/lnd.conf
  images/lnd/0.10.1-beta-ltc/start_tor.sh
  images/lnd/0.10.1-beta-ltc/supervisord.conf
  images/lnd/0.9.0-beta-ltc-simnet/patches/limits.patch
  images/lnd/0.9.0-beta-ltc/patches/checkpoints.patch
  images/utils/launcher/config/template.py
Labels: P1

#562 Add arby configuration options
  images/utils/launcher/config/config.py
  images/utils/launcher/config/mainnet.conf
  images/utils/launcher/config/simnet.conf
  images/utils/launcher/config/testnet.conf
  images/utils/launcher/node/arby.py
Labels: P1
