Repository ExchangeUnion/xud-docker, pull requests merged in 2020-04, with the labels that each got.

#378 fix: update Neutrino seed nodes
  images/lnd/0.9.0-beta-ltc/entrypoint.sh
  images/lnd/0.9.2-beta/entrypoint.sh
Labels: P2, enhancement

#403 fix: geth datadir hdd/ssd clarification
  images/utils/launcher/config/mainnet.conf
  images/utils/launcher/config/testnet.conf
Labels: P3

#394 chore(tools): fix git HEAD handling logic
  tools/helper.py
Labels: P3

#385 chore: update simnet images
  images/lnd/0.8.2-beta-simnet/Dockerfile
  images/lnd/0.8.2-beta-simnet/entrypoint.sh
  images/lnd/0.8.2-beta-simnet/lnd-btc.conf
  images/lnd/0.8.2-beta-simnet/lnd-ltc.conf
  images/lnd/0.8.2-beta-simnet/peers.sh
  images/lnd/0.8.2-beta-simnet/start_tor.sh
  images/lnd/0.8.2-beta-simnet/supervisord.conf
  images/lnd/0.9.0-beta-ltc-patched/Dockerfile
  images/lnd/0.9.0-beta-ltc-patched/entrypoint.sh
  images/lnd/0.9.0-beta-ltc-patched/patches/fundingmanager-ltc.patch
  images/lnd/0.9.0-beta-ltc-patched/patches/limits.patch
  images/lnd/0.9.0-beta-ltc-patched/patches/lnd.patch
  images/lnd/0.9.0-beta-ltc-patched/patches/neutrino.patch
  images/lnd/0.9.2-beta-patched/Dockerfile
  images/lnd/0.9.2-beta-patched/entrypoint.sh
  images/lnd/0.9.2-beta-patched/patches/fundingmanager-btc.patch
  images/lnd/0.9.2-beta-patched/patches/limits.patch
  images/lnd/0.9.2-beta-patched/patches/lnd.patch
  images/lnd/0.9.2-beta-patched/patches/neutrino.patch
  images/raiden/develop/Dockerfile
  images/raiden/develop/entrypoint.sh
  images/raiden/develop/onboarder.py
  images/utils/launcher/config/config.py
  images/utils/launcher/node/base.py
  images/utils/launcher/node/lnd.py
  images/utils/launcher/node/raiden.py
  images/utils/launcher/node/xud.py
  images/xud/1.0.0-beta.2-simnet/Dockerfile
  images/xud/1.0.0-beta.2-simnet/Dockerfile.aarch64
  images/xud/1.0.0-beta.2-simnet/entrypoint.sh
  images/xud/1.0.0-beta.2-simnet/supervisord.conf
  images/xud/1.0.0-beta.2-simnet/torrc
  images/xud/1.0.0-beta.2-simnet/xud.conf
  images/xud/latest/Dockerfile
  images/xud/latest/Dockerfile.aarch64
  images/xud/latest/entrypoint.sh
  images/xud/latest/start_tor.sh
  images/xud/latest/supervisord.conf
  images/xud/latest/torrc
  tests/integration/banner.txt
  tests/integration/test_light.py
  tests/integration/test_simnet.py
  tests/integration/utils.py
Labels: P1

#441 apply create/restore flow for simnet
  images/lnd/0.9.0-beta-ltc-patched/Dockerfile
  images/lnd/0.9.0-beta-ltc-patched/entrypoint.sh
  images/lnd/0.9.2-beta-patched/entrypoint.sh
  images/utils/launcher/__init__.py
  images/utils/launcher/auto_unlock.py
  images/utils/launcher/check_wallets.py
  images/utils/launcher/config/config.py
  images/utils/launcher/node/__init__.py
  images/utils/launcher/node/base.py
  images/utils/launcher/node/lnd.py
  images/utils/launcher/node/xud.py
  images/xud/latest/entrypoint.sh
Labels: P1
