Repository ExchangeUnion/xud-docker, pull requests merged in 2020-08, with the labels that each got.

#646 feat(arby): add configurable trading pair
  images/utils/launcher/config/config.py
  images/utils/launcher/config/mainnet.conf
  images/utils/launcher/config/simnet.conf
  images/utils/launcher/config/template.py
  images/utils/launcher/config/testnet.conf
  images/utils/launcher/node/arby.py
Labels: P1

#654 feat: upgrade connext to 7.1.2
  images/connext/src.py
  images/utils/launcher/config/template.py
Labels: P1

#677 chore: upgrade lndbtc/lndltc to 0.11 and enable wumbo, rm simnet limit patches
  images/lndbtc-simnet/entrypoint.sh
  images/lndbtc-simnet/patches/apply.sh
  images/lndbtc-simnet/patches/fundingmanager.patch
  images/lndbtc-simnet/patches/limits.patch
  images/lndbtc-simnet/src.py
  images/lndbtc/lnd.conf
  images/lndbtc/src.py
  images/lndltc-simnet/entrypoint.sh
  images/lndltc-simnet/patches/apply.sh
  images/lndltc-simnet/patches/fundingmanager.patch
  images/lndltc-simnet/patches/limits.patch
  images/lndltc-simnet/src.py
  images/lndltc/lnd.conf
  images/lndltc/src.py
  images/utils/launcher/config/template.py
Labels: P2

#639 fix: update decline in a simple way
  images/utils/launcher/__init__.py
  images/utils/launcher/node/DockerTemplate.py
  images/utils/launcher/node/__init__.py
  images/utils/launcher/node/base.py
Labels: P1

#689 chore: upgrade geth 1.9.19 -> 1.9.20
  images/geth/src.py
  images/utils/launcher/config/template.py
Labels: P3

#687 feat(arby): upgrade mainnet to v1.1.8
  images/utils/launcher/config/template.py
Labels: P1

#697 chore: upgrade connext client 1.3.0 -> 1.3.1
  images/connext/src.py
  images/utils/launcher/config/template.py
Labels: P1

#703 chore: upgrade connext 1.3.1 -> 1.3.2
  images/connext/src.py
  images/utils/launcher/config/template.py
Labels: P1
