Repository ExchangeUnion/xud-docker, pull requests merged in 2020-03, with the labels that each got.

#356 feat: add Neutrino to Litecoin LND
  images/lnd/0.9.0-beta-ltc/Dockerfile
  images/lnd/0.9.0-beta-ltc/entrypoint.sh
  images/lnd/0.9.0-beta-ltc/lnd.conf
  images/lnd/0.9.0-beta-ltc/patches/checkpoints.patch
  images/lnd/0.9.0-beta-ltc/start_tor.sh
  images/lnd/0.9.0-beta-ltc/supervisord.conf
  images/lnd/0.9.2-beta/Dockerfile
  images/lnd/0.9.2-beta/entrypoint.sh
  images/lnd/0.9.2-beta/lnd.conf
  images/lnd/0.9.2-beta/start_tor.sh
  images/lnd/0.9.2-beta/supervisord.conf
  images/utils/launcher/config/config.py
  images/utils/launcher/config/mainnet.conf
  images/utils/launcher/config/testnet.conf
  nodes.json
Labels: enhancement

#343 feat: add mode config option
  images/utils/launcher/config/mainnet.conf
  images/utils/launcher/config/testnet.conf
Labels: P1, needs testing

#337 fix: name collision when running multiple utils containers
  images/utils/launcher/__init__.py
  images/utils/launcher/close_other_utils.py
  setup.sh
Labels: P2, bug
