Repository ExchangeUnion/xud-docker, pull requests merged in 2020-05, with the labels that each got.

#451 chore: refine tools scripts to build xud:latest in time
  tools/helper.py
Labels: P1

#454 fix: add a fallback plan to get xud revision and branch
  tools/helper.py
Labels: P1

#429 feat: connext
  images/connext/latest/Dockerfile
  images/connext/latest/Dockerfile.aarch64
  images/connext/latest/entrypoint.sh
  images/connext/latest/supervisord.conf
  images/lnd/0.10.0-beta-patched/Dockerfile
  images/lnd/0.10.0-beta-patched/entrypoint.sh
  images/lnd/0.10.0-beta-patched/patches/fundingmanager-btc.patch
  images/lnd/0.10.0-beta-patched/patches/limits.patch
  images/lnd/0.10.0-beta-patched/patches/lnd.patch
  images/lnd/0.10.0-beta-patched/patches/neutrino.patch
  images/lnd/0.9.0-beta-ltc-patched/Dockerfile
  images/lnd/0.9.0-beta-ltc-patched/entrypoint.sh
  images/lnd/0.9.0-beta-ltc/Dockerfile
  images/lnd/0.9.2-beta/Dockerfile
  images/utils/launcher/__init__.py
  images/utils/launcher/auto_unlock.py
  images/utils/launcher/check_wallets.py
  images/utils/launcher/config/config.py
  images/utils/launcher/config/simnet.conf
  images/utils/launcher/config/testnet.conf
  images/utils/launcher/node/__init__.py
  images/utils/launcher/node/base.py
  images/utils/launcher/node/connext.py
  images/utils/launcher/node/lnd.py
  images/utils/launcher/node/xud.py
  images/xud/latest/Dockerfile
  images/xud/latest/Dockerfile.aarch64
  images/xud/latest/entrypoint.sh
  requirements-dev.txt
  tests/integration/test_simnet.py
  tools/helper.py
Labels: P1

#463 fix: add neutrino assumechanvalid option to fix sync
  images/lnd/0.10.0-beta-simnet/Dockerfile
  images/lnd/0.10.0-beta-simnet/entrypoint.sh
  images/lnd/0.10.0-beta-simnet/patches/fundingmanager-btc.patch
  images/lnd/0.10.0-beta-simnet/patches/limits.patch
  images/lnd/0.10.0-beta-simnet/patches/lnd.patch
  images/lnd/0.10.0-beta-simnet/patches/neutrino.patch
  images/lnd/0.10.0-beta/Dockerfile
  images/lnd/0.10.0-beta/entrypoint.sh
  images/lnd/0.10.0-beta/lnd.conf
  images/lnd/0.10.0-beta/start_tor.sh
  images/lnd/0.10.0-beta/supervisord.conf
  images/lnd/0.9.0-beta-ltc-simnet/Dockerfile
  images/lnd/0.9.0-beta-ltc-simnet/entrypoint.sh
  images/lnd/0.9.0-beta-ltc-simnet/patches/fundingmanager-ltc.patch
  images/lnd/0.9.0-beta-ltc-simnet/patches/limits.patch
  images/lnd/0.9.0-beta-ltc-simnet/patches/lnd.patch
  images/lnd/0.9.0-beta-ltc-simnet/patches/neutrino.patch
  images/lnd/0.9.0-beta-ltc/Dockerfile
  images/lnd/0.9.0-beta-ltc/entrypoint.sh
  images/utils/launcher/config/config.py
  images/utils/launcher/node/lnd.py
  nodes.json
Labels: P1

#473 downgrade go for lnd's to 1.13
  images/lnd/0.10.0-beta-simnet/Dockerfile
  images/lnd/0.10.0-beta/Dockerfile
  images/lnd/0.9.0-beta-ltc-simnet/Dockerfile
  images/lnd/0.9.0-beta-ltc/Dockerfile
Labels: bug

#474 chore: update xud-docker link to docs
  README.md
Labels: enhancement, for-market-makers
