Repository ExchangeUnion/xud-docker, pull requests merged in 2020-07, with the labels that each got.

#532 feat: add Boltz daemon
  images/boltz/1.0.0/Dockerfile
  images/boltz/1.0.0/entrypoint.sh
  images/boltz/1.0.0/supervisord.conf
  images/boltz/1.0.0/wrapper.sh
  images/boltz/latest/Dockerfile
  images/boltz/latest/entrypoint.sh
  images/boltz/latest/supervisord.conf
  images/boltz/latest/wrapper.sh
  images/utils/launcher/__init__.py
  images/utils/launcher/config/config.py
  images/utils/launcher/config/template.py
  images/utils/launcher/config/testnet.conf
  images/utils/launcher/node/__init__.py
  images/utils/launcher/node/boltz.py
Labels: P1

#585 chore: upgrade lndbtc 0.10.1 -> 0.10.2
  images/lnd/0.10.2-beta-simnet/Dockerfile
  images/lnd/0.10.2-beta-simnet/entrypoint.sh
  images/lnd/0.10.2-beta-simnet/patches/fundingmanager-btc.patch
  images/lnd/0.10.2-beta-simnet/patches/limits.patch
  images/lnd/0.10.2-beta-simnet/patches/lnd.patch
  images/lnd/0.10.2-beta-simnet/patches/neutrino.patch
  images/lnd/0.10.2-beta/Dockerfile
  images/lnd/0.10.2-beta/entrypoint.sh
  images/lnd/0.10.2-beta/lnd.conf
  images/lnd/0.10.2-beta/start_tor.sh
  images/lnd/0.10.2-beta/supervisord.conf
  images/utils/launcher/config/template.py
Labels: P2

#582 feat: add webui
  images/utils/launcher/config/config.py
  images/utils/launcher/config/mainnet.conf
  images/utils/launcher/config/simnet.conf
  images/utils/launcher/config/template.py
  images/utils/launcher/config/testnet.conf
  images/utils/launcher/node/__init__.py
  images/utils/launcher/node/webui.py
  images/webui/latest/Dockerfile
  images/webui/latest/Dockerfile.aarch64
  images/webui/latest/entrypoint.sh
  images/webui/latest/supervisord.conf
  requirements-dev.txt
Labels: P2

#597 chore: upgrade geth 1.9.15 -> 1.9.16
  images/geth/1.9.16/Dockerfile
  images/geth/1.9.16/entrypoint.sh
  images/geth/1.9.16/mainnet-peers.txt
  images/geth/1.9.16/rinkeby-peers.txt
  images/utils/launcher/config/template.py
Labels: P3

#632 feat: use release version for latest tags of bitcoind, litecoind, geth and lnd
  images/bitcoind/src.py
  images/geth/src.py
  images/litecoind/src.py
  images/lnd/.dockerignore
  images/lnd/src.py
  images/lndbtc-simnet/.dockerignore
  images/lndbtc-simnet/Dockerfile
  images/lndbtc-simnet/entrypoint.sh
  images/lndbtc-simnet/patches/apply.sh
  images/lndbtc-simnet/patches/fundingmanager.patch
  images/lndbtc-simnet/patches/limits.patch
  images/lndbtc-simnet/patches/lnd.patch
  images/lndbtc-simnet/patches/neutrino.patch
  images/lndbtc-simnet/src.py
  images/lndbtc/.dockerignore
  images/lndbtc/Dockerfile
  images/lndbtc/entrypoint.sh
  images/lndbtc/lnd.conf
  images/lndbtc/src.py
  images/lndbtc/start_tor.sh
  images/lndbtc/supervisord.conf
  images/lndbtc/torrc
  images/lndbtc/wait-file.sh
  images/lndltc-simnet/.dockerignore
  images/lndltc-simnet/Dockerfile
  images/lndltc-simnet/entrypoint.sh
  images/lndltc-simnet/patches/apply.sh
  images/lndltc-simnet/patches/fundingmanager.patch
  images/lndltc-simnet/patches/limits.patch
  images/lndltc-simnet/patches/lnd.patch
  images/lndltc-simnet/patches/neutrino.patch
  images/lndltc-simnet/src.py
  images/lndltc/.dockerignore
  images/lndltc/Dockerfile
  images/lndltc/entrypoint.sh
  images/lndltc/lnd.conf
  images/lndltc/src.py
  images/lndltc/start_tor.sh
  images/lndltc/supervisord.conf
  images/lndltc/torrc
  images/lndltc/wait-file.sh
  images/utils/launcher/config/template.py
Labels: P1, bug
