Repository ExchangeUnion/xud-docker, pull requests merged in 2020-02, with the labels that each got.

#276 chore: cleanup
  .travis.yml
  init.sh
  status.sh
  status2.sh
  tests/centos-6/Vagrantfile
  tests/centos-6/init.sh
  tests/centos-7/Vagrantfile
  tests/centos-7/init.sh
  tests/run_test.sh
  tests/run_vagrant_test.sh
  tests/second_run.exp
  tests/sync.sh
  tests/terraform/.gitignore
  tests/terraform/init.sh
  tests/terraform/main.tf
  tests/testnet.exp
  tests/ubuntu-14/Vagrantfile
  tests/ubuntu-14/init.sh
  tests/ubuntu-16/Vagrantfile
  tests/ubuntu-16/init.sh
  tests/ubuntu-18/Vagrantfile
  tests/ubuntu-18/init.sh
  xud-mainnet/docker-compose.yml
  xud-regtest/.env
  xud-regtest/README.md
  xud-regtest/aliases.bash
  xud-regtest/btcd/Dockerfile
  xud-regtest/btcd/entrypoint.sh
  xud-regtest/btcd/init.py
  xud-regtest/docker-compose.yml
  xud-regtest/install.sh
  xud-regtest/lnd/Dockerfile
  xud-regtest/lnd/entrypoint.sh
  xud-regtest/ltcd/Dockerfile
  xud-regtest/ltcd/entrypoint.sh
  xud-regtest/ltcd/init.py
  xud-regtest/uninstall.sh
  xud-regtest/xud/Dockerfile
  xud-regtest/xud/entrypoint.sh
  xud-regtest/xud/xud.conf
  xud-simnet/docker-compose.yml
  xud-testnet/docker-compose.yml
Labels: P3

#259 feat: build all images on aarch64 architecture
  images/bitcoind/Dockerfile.aarch64
  images/geth/Dockerfile.aarch64
  images/geth/entrypoint.sh
  images/litecoind/Dockerfile.aarch64
  images/lnd-simnet/Dockerfile.aarch64
  images/lnd/Dockerfile.aarch64
  images/ltcd-simnet/Dockerfile.aarch64
  images/raiden-simnet/Dockerfile.aarch64
  images/utils/launcher/node/base.py
  images/xud-simnet/Dockerfile.aarch64
  images/xud/Dockerfile.aarch64
  supports/Dockerfile.aarch64
  supports/install.sh
  tools/helper.py
Labels: P1

#289 chore: update GETH to v1.9.10
  images/utils/launcher/node/geth.py
  images/versions.ini
Labels: P3

#288 feat: allow Neutrino on LND BTC
  images/lnd/entrypoint.sh
  images/utils/args_parser.py
  images/utils/launcher/config/config.py
  images/utils/launcher/config/mainnet.conf
  images/utils/launcher/config/testnet.conf
  images/utils/launcher/node/bitcoind.py
  images/utils/launcher/node/lnd.py
Labels: P1

#299 feat: update GETH and LND images
  images/utils/launcher/node/geth.py
  images/utils/launcher/node/lnd.py
  images/versions.ini
Labels: P1

#303 feat(tor): use native xud-tor integration
  images/xud-simnet/Dockerfile
  images/xud-simnet/Dockerfile.aarch64
  images/xud-simnet/entrypoint.sh
  images/xud-simnet/proxychains4.conf
  images/xud-simnet/xud.conf
  images/xud/Dockerfile
  images/xud/Dockerfile.aarch64
  images/xud/entrypoint.sh
  images/xud/proxychains4.conf
  images/xud/xud.conf
  supports/Dockerfile
Labels: P2
